include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - '**/*.g.dart'
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations