name: shoppings_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  go_router: ^14.8.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.5.2
  collection: ^1.19.0
  intl: ^0.20.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  go_router_builder: ^2.8.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env